### ISSUE TITLE
Did you forget to call SetImages()?

### ISSUE THREAD

**Issue by nmweizi** [lijiejie/EasyPen#4]
python3.10 EasyPen.py
21:16:25: Debug: Adding duplicate image handler for 'Windows bitmap file'
21:16:25: Debug: Adding duplicate animation handler for '1' type
21:16:25: Debug: Adding duplicate animation handler for '2' type
21:16:28: Debug: Adding duplicate image handler for 'Windows bitmap file'
21:16:28: Debug: Adding duplicate animation handler for '1' type
21:16:28: Debug: Adding duplicate animation handler for '2' type
21:16:28: Debug: Adding duplicate image handler for 'Windows bitmap file'
21:16:28: Debug: Adding duplicate animation handler for '1' type
21:16:28: Debug: Adding duplicate animation handler for '2' type
Traceback (most recent call last):
  File "/Users/aaa/tools/EasyPen/ui/frame_loading.py", line 48, in on_close
    frame = MainFrame(None, "EasyPen %s" % conf.app_ver)
  File "/Users/aaaa/tools/EasyPen/ui/frame_main.py", line 105, in __init__
    self.notebook.AddPage(discover_panel, "Discover", imageId=0)
wx._core.wxAssertionError: C++ assertion ""Assert failure"" failed at /Users/robind/projects/bb2/dist-osx-py310/build/ext/wxWidgets/include/wx/withimages.h(195) in GetBitmapBundle(): Image index specified, but there are no images.

Did you forget to call SetImages()?

**Comment by nmweizi** [comment]
macos
if 'wxMac' not in wx.PlatformInfo:?

**Comment by lijiejie** [comment]
Hi, this app not yet tested under MacOS since I got no MacOS device at present.
I may test it under MacOS  in the coming future.

**Comment by nmweizi** [comment]
> Hi, this app not yet tested under MacOS since I got no MacOS device at present. I may test it under MacOS in the coming future.

取消这个判断，macos启动正常

**Comment by lijiejie** [comment]
> > Hi, this app not yet tested under MacOS since I got no MacOS device at present. I may test it under MacOS in the coming future.
> 
> 取消这个判断，macos启动正常

方便提交一个PR吗？ 这样后面你若发现其他问题，还可以把代码合并进来

**Comment by nmweizi** [comment]
@lijiejie 
https://github.com/lijiejie/EasyPen/pull/5#issue-1387652003
